# Generated by Django 5.0.2 on 2025-04-23 20:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="organization",
            name="unique_name_per_parent",
        ),
        migrations.AlterUniqueTogether(
            name="organization",
            unique_together={("parent", "name")},
        ),
    ]
