# Generated by Django 5.0.2 on 2025-04-23 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0002_remove_organization_unique_name_per_parent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="organization.organization",
                verbose_name="父级区域",
            ),
        ),
    ]
