name: Documentation

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/src/**'
      - 'backend1/apps/**'
      - 'docs/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend/src/**'
      - 'backend1/apps/**'
      - 'docs/**'
      - '.github/workflows/docs.yml'
  schedule:
    - cron: '0 0 * * 0'  # 每周日运行

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        cd backend1
        pip install -r requirements/development.txt
        
    - name: Build backend documentation
      run: |
        cd backend1
        cd docs
        make html
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install Node.js dependencies
      run: |
        cd frontend
        npm install
        
    - name: Build frontend documentation
      run: |
        cd frontend
        npm run docs
        
    - name: Build VuePress documentation
      run: |
        cd frontend
        npm run docs:build
        
    - name: Start backend server
      run: |
        cd backend1
        python manage.py runserver 0.0.0.0:8000 &
        sleep 10
        
    - name: Sync API documentation
      run: |
        node scripts/sync-api-docs.js
      continue-on-error: true
        
    - name: Check for outdated documentation
      run: |
        node scripts/check-outdated-docs.js
      continue-on-error: true
        
    - name: Create issue if documentation is outdated
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: '文档需要更新',
            body: '检测到文档与代码不同步，请及时更新。'
          })
          
    - name: Generate changelog
      run: |
        node scripts/generate-changelog.js
      continue-on-error: true
        
    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: |
          frontend/docs
          backend1/docs/_build/html
        retention-days: 30 